Repository cloudnode-pro/CloudnodeMSG, pull requests merged in 2024-01, with the labels that each got.

#7 Add `/message` and `/cloudnodemsg` commands
  src/main/java/pro/cloudnode/smp/cloudnodemsg/CloudnodeMSG.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/Permission.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/PluginConfig.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/Command.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/MainCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/MessageCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/Error.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/InvalidPlayerError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/MessageYourselfError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/NoPermissionError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/PlayerNotFoundError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/message/Message.java
  src/main/resources/config.yml
  src/main/resources/plugin.yml
Labels: feature

#8 Add `/reply`
  src/main/java/pro/cloudnode/smp/cloudnodemsg/CloudnodeMSG.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/PluginConfig.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ReplyCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/NobodyReplyError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/ReplyOfflineError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/message/Message.java
  src/main/resources/config.yml
  src/main/resources/plugin.yml
Labels: feature

#12 Prevent messaging vanished players
  src/main/java/pro/cloudnode/smp/cloudnodemsg/CloudnodeMSG.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/Permission.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/MessageCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ReplyCommand.java
Labels: feature

#15 Make our commands async
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/Command.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/IgnoreCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/MainCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/MessageCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ReplyCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/UnIgnoreCommand.java
Labels: bug

#16 Create Maven build CI as GitHub action
  .github/workflows/maven.yml
Labels: enhancement

#18 Fix Javadoc comments in Error classes
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/InvalidPlayerError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/MessageYourselfError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/NeverJoinedError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/NoPermissionError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/NobodyReplyError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/NotIgnoredError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/NotPlayerError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/PlayerNotFoundError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/ReplyOfflineError.java
Labels: bug, enhancement

#20 JavaDodcs on GitHub pages
  .github/workflows/docs.yml
  pom.xml
Labels: documentation

#19 Also ingore public chat messages when using `/ignore`
  src/main/java/pro/cloudnode/smp/cloudnodemsg/CloudnodeMSG.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/Permission.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/IgnoreCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/listener/AsyncChatListener.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/message/Message.java
Labels: enhancement

#21 Set correct default branch name
  .github/workflows/docs.yml
Labels: bug, documentation

#22 Use a single job in the javadocs deploy workflow
  .github/workflows/docs.yml
Labels: bug, documentation

#23 Fix the command used to generate JavaDoc
  .github/workflows/docs.yml
Labels: bug, documentation

#27 Add release workflow
  .github/workflows/release.yml
Labels: documentation

#26 Implements an option to toggle private messages
  src/main/java/pro/cloudnode/smp/cloudnodemsg/CloudnodeMSG.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/Permission.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/PluginConfig.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/MessageCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ReplyCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ToggleMessageCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/error/PlayerHasIncomingDisabledError.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/message/Message.java
  src/main/resources/config.yml
  src/main/resources/plugin.yml
Labels: enhancement, feature

#30 Add DM channels
  src/main/java/pro/cloudnode/smp/cloudnodemsg/PluginConfig.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/MessageCommand.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/listener/AsyncChatListener.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/message/Message.java
  src/main/resources/config.yml
Labels: feature

#32 Add spying
  src/main/java/pro/cloudnode/smp/cloudnodemsg/Permission.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/PluginConfig.java
  src/main/java/pro/cloudnode/smp/cloudnodemsg/message/Message.java
  src/main/resources/config.yml
Labels: feature

#31 Fix replying to console messages
  src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ReplyCommand.java
Labels: bug
